server:
  port: 8081

spring:
  application:
    name: hmdp
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${dp.datasource.host}:${dp.datasource.port}/${dp.datasource.database}?useSSL=false&serverTimezone=UTC
    username: ${dp.datasource.username}
    password: ${dp.datasource.password}
  redis:
    host: ${dp.redis.host}
    port: ${dp.redis.port}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: NON_NULL # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com:
      hmdp: debug